from email.message import EmailMessage
import ssl
import smtplib

# specify the email adress and the password generated for your app below:
email_sender = '' # your_email_address
email_password = '' #password generated by gmail for your application

# type the email adress of the reviever
email_reciever = ''

# enter a subject
subject = 'Shopping List reminder'

# the body of the email
body = """
1. Mangoes
2. Herseys
3. Cooking Oil
4. Peanuts
5. Merlot
"""

# create an EmailMessage instance and specify the sender, reciever, content and subject
em = EmailMessage()
em['From'] = email_sender
em['To'] = email_reciever
em['subject'] = subject
em.set_content(body)

# create a context to login and send the email
context = ssl.create_default_context()

# use ssl and smtplib to send the email
with smtplib.SMTP_SSL('smtp.gmail.com', 465, context = context) as smtp:
    smtp.login(email_sender, email_password)
    smtp.sendmail(email_sender, email_reciever, em.as_string())

